name: iOS Dylib Build
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile Dylib
        run: |
          clang++ -dynamiclib -arch arm64 \
          -isysroot $(xcrun --sdk iphoneos --show-sdk-path) \
          -o MyExecutor.dylib main.cpp -std=c++17
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyCompiledExecutor
          path: MyExecutor.dylib
